import joblib
import json
import os

from fastapi import FastAPI
import pandas as pd
from pydantic import BaseModel
from utils import create_samples


app = FastAPI()
with open('models/pipe.pkl', 'rb') as file:
    model = joblib.load(file)

df = pd.read_csv('samples/samples.csv')
create_samples(df)

class Form(BaseModel):
    id: int
    rn: int
    pre_since_opened_0: int
    pre_since_opened_1: int
    pre_since_opened_2: int
    pre_since_opened_3: int
    pre_since_opened_4: int
    pre_since_opened_5: int
    pre_since_opened_6: int
    pre_since_opened_7: int
    pre_since_opened_8: int
    pre_since_opened_9: int
    pre_since_opened_10: int
    pre_since_opened_11: int
    pre_since_opened_12: int
    pre_since_opened_13: int
    pre_since_opened_14: int
    pre_since_opened_15: int
    pre_since_opened_16: int
    pre_since_opened_17: int
    pre_since_opened_18: int
    pre_since_opened_19: int
    pre_since_confirmed_0: int
    pre_since_confirmed_1: int
    pre_since_confirmed_2: int
    pre_since_confirmed_3: int
    pre_since_confirmed_4: int
    pre_since_confirmed_5: int
    pre_since_confirmed_6: int
    pre_since_confirmed_7: int
    pre_since_confirmed_8: int
    pre_since_confirmed_9: int
    pre_since_confirmed_10: int
    pre_since_confirmed_11: int
    pre_since_confirmed_12: int
    pre_since_confirmed_13: int
    pre_since_confirmed_14: int
    pre_since_confirmed_15: int
    pre_since_confirmed_16: int
    pre_since_confirmed_17: int
    pre_pterm_0: int
    pre_pterm_1: int
    pre_pterm_2: int
    pre_pterm_3: int
    pre_pterm_4: int
    pre_pterm_5: int
    pre_pterm_6: int
    pre_pterm_7: int
    pre_pterm_8: int
    pre_pterm_9: int
    pre_pterm_10: int
    pre_pterm_11: int
    pre_pterm_12: int
    pre_pterm_13: int
    pre_pterm_14: int
    pre_pterm_15: int
    pre_pterm_16: int
    pre_pterm_17: int
    pre_fterm_0: int
    pre_fterm_1: int
    pre_fterm_2: int
    pre_fterm_3: int
    pre_fterm_4: int
    pre_fterm_5: int
    pre_fterm_6: int
    pre_fterm_7: int
    pre_fterm_8: int
    pre_fterm_9: int
    pre_fterm_10: int
    pre_fterm_11: int
    pre_fterm_12: int
    pre_fterm_13: int
    pre_fterm_14: int
    pre_fterm_15: int
    pre_fterm_16: int
    pre_till_pclose_0: int
    pre_till_pclose_1: int
    pre_till_pclose_2: int
    pre_till_pclose_3: int
    pre_till_pclose_4: int
    pre_till_pclose_5: int
    pre_till_pclose_6: int
    pre_till_pclose_7: int
    pre_till_pclose_8: int
    pre_till_pclose_9: int
    pre_till_pclose_10: int
    pre_till_pclose_11: int
    pre_till_pclose_12: int
    pre_till_pclose_13: int
    pre_till_pclose_14: int
    pre_till_pclose_15: int
    pre_till_pclose_16: int
    pre_till_fclose_0: int
    pre_till_fclose_1: int
    pre_till_fclose_2: int
    pre_till_fclose_3: int
    pre_till_fclose_4: int
    pre_till_fclose_5: int
    pre_till_fclose_6: int
    pre_till_fclose_7: int
    pre_till_fclose_8: int
    pre_till_fclose_9: int
    pre_till_fclose_10: int
    pre_till_fclose_11: int
    pre_till_fclose_12: int
    pre_till_fclose_13: int
    pre_till_fclose_14: int
    pre_till_fclose_15: int
    pre_loans_credit_limit_0: int
    pre_loans_credit_limit_1: int
    pre_loans_credit_limit_2: int
    pre_loans_credit_limit_3: int
    pre_loans_credit_limit_4: int
    pre_loans_credit_limit_5: int
    pre_loans_credit_limit_6: int
    pre_loans_credit_limit_7: int
    pre_loans_credit_limit_8: int
    pre_loans_credit_limit_9: int
    pre_loans_credit_limit_10: int
    pre_loans_credit_limit_11: int
    pre_loans_credit_limit_12: int
    pre_loans_credit_limit_13: int
    pre_loans_credit_limit_14: int
    pre_loans_credit_limit_15: int
    pre_loans_credit_limit_16: int
    pre_loans_credit_limit_17: int
    pre_loans_credit_limit_18: int
    pre_loans_credit_limit_19: int
    pre_loans_next_pay_summ_0: int
    pre_loans_next_pay_summ_1: int
    pre_loans_next_pay_summ_2: int
    pre_loans_next_pay_summ_3: int
    pre_loans_next_pay_summ_4: int
    pre_loans_next_pay_summ_5: int
    pre_loans_next_pay_summ_6: int
    pre_loans_outstanding_1: int
    pre_loans_outstanding_2: int
    pre_loans_outstanding_3: int
    pre_loans_outstanding_4: int
    pre_loans_outstanding_5: int
    pre_loans_total_overdue_0: int
    pre_loans_max_overdue_sum_1: int
    pre_loans_max_overdue_sum_2: int
    pre_loans_max_overdue_sum_3: int
    pre_loans_credit_cost_rate_0: int
    pre_loans_credit_cost_rate_1: int
    pre_loans_credit_cost_rate_2: int
    pre_loans_credit_cost_rate_3: int
    pre_loans_credit_cost_rate_4: int
    pre_loans_credit_cost_rate_5: int
    pre_loans_credit_cost_rate_6: int
    pre_loans_credit_cost_rate_7: int
    pre_loans_credit_cost_rate_8: int
    pre_loans_credit_cost_rate_9: int
    pre_loans_credit_cost_rate_10: int
    pre_loans_credit_cost_rate_11: int
    pre_loans_credit_cost_rate_12: int
    pre_loans_credit_cost_rate_13: int
    pre_loans5_0: int
    pre_loans5_1: int
    pre_loans5_2: int
    pre_loans5_3: int
    pre_loans5_5: int
    pre_loans5_6: int
    pre_loans5_7: int
    pre_loans5_13: int
    pre_loans5_16: int
    pre_loans530_0: int
    pre_loans530_1: int
    pre_loans530_2: int
    pre_loans530_3: int
    pre_loans530_4: int
    pre_loans530_6: int
    pre_loans530_7: int
    pre_loans530_10: int
    pre_loans530_11: int
    pre_loans530_12: int
    pre_loans530_13: int
    pre_loans530_14: int
    pre_loans530_15: int
    pre_loans530_16: int
    pre_loans530_18: int
    pre_loans530_19: int
    pre_loans3060_1: int
    pre_loans3060_2: int
    pre_loans3060_5: int
    pre_loans3060_7: int
    pre_loans3060_8: int
    pre_loans3060_9: int
    pre_loans6090_1: int
    pre_loans6090_2: int
    pre_loans6090_3: int
    pre_loans6090_4: int
    pre_loans90_2: int
    pre_loans90_8: int
    pre_loans90_13: int
    pre_loans90_14: int
    pre_loans90_19: int
    is_zero_loans5_0: int
    is_zero_loans5_1: int
    is_zero_loans530_0: int
    is_zero_loans530_1: int
    is_zero_loans3060_0: int
    is_zero_loans3060_1: int
    is_zero_loans6090_0: int
    is_zero_loans6090_1: int
    is_zero_loans90_0: int
    is_zero_loans90_1: int
    pre_util_0: int
    pre_util_1: int
    pre_util_2: int
    pre_util_3: int
    pre_util_4: int
    pre_util_5: int
    pre_util_6: int
    pre_util_7: int
    pre_util_8: int
    pre_util_9: int
    pre_util_10: int
    pre_util_11: int
    pre_util_12: int
    pre_util_13: int
    pre_util_14: int
    pre_util_15: int
    pre_util_16: int
    pre_util_17: int
    pre_util_18: int
    pre_util_19: int
    pre_over2limit_0: int
    pre_over2limit_1: int
    pre_over2limit_2: int
    pre_over2limit_3: int
    pre_over2limit_4: int
    pre_over2limit_5: int
    pre_over2limit_6: int
    pre_over2limit_7: int
    pre_over2limit_8: int
    pre_over2limit_9: int
    pre_over2limit_10: int
    pre_over2limit_11: int
    pre_over2limit_12: int
    pre_over2limit_13: int
    pre_over2limit_14: int
    pre_over2limit_15: int
    pre_over2limit_16: int
    pre_over2limit_17: int
    pre_over2limit_18: int
    pre_over2limit_19: int
    pre_maxover2limit_0: int
    pre_maxover2limit_1: int
    pre_maxover2limit_2: int
    pre_maxover2limit_3: int
    pre_maxover2limit_4: int
    pre_maxover2limit_5: int
    pre_maxover2limit_6: int
    pre_maxover2limit_7: int
    pre_maxover2limit_8: int
    pre_maxover2limit_9: int
    pre_maxover2limit_10: int
    pre_maxover2limit_11: int
    pre_maxover2limit_12: int
    pre_maxover2limit_13: int
    pre_maxover2limit_14: int
    pre_maxover2limit_15: int
    pre_maxover2limit_16: int
    pre_maxover2limit_17: int
    pre_maxover2limit_18: int
    pre_maxover2limit_19: int
    is_zero_util_0: int
    is_zero_util_1: int
    is_zero_over2limit_0: int
    is_zero_over2limit_1: int
    is_zero_maxover2limit_0: int
    is_zero_maxover2limit_1: int
    enc_paym_0_0: int
    enc_paym_0_1: int
    enc_paym_0_2: int
    enc_paym_0_3: int
    enc_paym_1_0: int
    enc_paym_1_1: int
    enc_paym_1_2: int
    enc_paym_1_3: int
    enc_paym_2_0: int
    enc_paym_2_1: int
    enc_paym_2_2: int
    enc_paym_2_3: int
    enc_paym_3_0: int
    enc_paym_3_1: int
    enc_paym_3_2: int
    enc_paym_3_3: int
    enc_paym_4_0: int
    enc_paym_4_1: int
    enc_paym_4_2: int
    enc_paym_4_3: int
    enc_paym_5_0: int
    enc_paym_5_1: int
    enc_paym_5_2: int
    enc_paym_5_3: int
    enc_paym_6_0: int
    enc_paym_6_1: int
    enc_paym_6_2: int
    enc_paym_6_3: int
    enc_paym_7_0: int
    enc_paym_7_1: int
    enc_paym_7_2: int
    enc_paym_7_3: int
    enc_paym_8_0: int
    enc_paym_8_1: int
    enc_paym_8_2: int
    enc_paym_8_3: int
    enc_paym_9_0: int
    enc_paym_9_1: int
    enc_paym_9_2: int
    enc_paym_9_3: int
    enc_paym_10_0: int
    enc_paym_10_1: int
    enc_paym_10_2: int
    enc_paym_10_3: int
    enc_paym_11_1: int
    enc_paym_11_2: int
    enc_paym_11_3: int
    enc_paym_11_4: int
    enc_paym_12_0: int
    enc_paym_12_1: int
    enc_paym_12_2: int
    enc_paym_12_3: int
    enc_paym_13_0: int
    enc_paym_13_1: int
    enc_paym_13_2: int
    enc_paym_13_3: int
    enc_paym_14_0: int
    enc_paym_14_1: int
    enc_paym_14_2: int
    enc_paym_14_3: int
    enc_paym_15_0: int
    enc_paym_15_1: int
    enc_paym_15_2: int
    enc_paym_15_3: int
    enc_paym_16_0: int
    enc_paym_16_1: int
    enc_paym_16_2: int
    enc_paym_16_3: int
    enc_paym_17_0: int
    enc_paym_17_1: int
    enc_paym_17_2: int
    enc_paym_17_3: int
    enc_paym_18_0: int
    enc_paym_18_1: int
    enc_paym_18_2: int
    enc_paym_18_3: int
    enc_paym_19_0: int
    enc_paym_19_1: int
    enc_paym_19_2: int
    enc_paym_19_3: int
    enc_paym_20_1: int
    enc_paym_20_2: int
    enc_paym_20_3: int
    enc_paym_20_4: int
    enc_paym_21_0: int
    enc_paym_21_1: int
    enc_paym_21_2: int
    enc_paym_21_3: int
    enc_paym_22_0: int
    enc_paym_22_1: int
    enc_paym_22_2: int
    enc_paym_22_3: int
    enc_paym_23_0: int
    enc_paym_23_1: int
    enc_paym_23_2: int
    enc_paym_23_3: int
    enc_paym_24_1: int
    enc_paym_24_2: int
    enc_paym_24_3: int
    enc_paym_24_4: int
    enc_loans_account_holder_type_0: int
    enc_loans_account_holder_type_1: int
    enc_loans_account_holder_type_2: int
    enc_loans_account_holder_type_3: int
    enc_loans_account_holder_type_4: int
    enc_loans_account_holder_type_5: int
    enc_loans_account_holder_type_6: int
    enc_loans_credit_status_0: int
    enc_loans_credit_status_1: int
    enc_loans_credit_status_2: int
    enc_loans_credit_status_3: int
    enc_loans_credit_status_4: int
    enc_loans_credit_status_5: int
    enc_loans_credit_status_6: int
    enc_loans_credit_type_0: int
    enc_loans_credit_type_1: int
    enc_loans_credit_type_2: int
    enc_loans_credit_type_3: int
    enc_loans_credit_type_4: int
    enc_loans_credit_type_5: int
    enc_loans_account_cur_0: int
    enc_loans_account_cur_1: int
    enc_loans_account_cur_2: int
    enc_loans_account_cur_3: int
    pclose_flag_0: int
    pclose_flag_1: int
    fclose_flag_0: int
    fclose_flag_1: int
    pre_loans_total_overdue_1: int
    pre_loans_max_overdue_sum_0: int
    pre_loans5_8: int
    pre_loans5_9: int
    pre_loans90_10: int
    enc_loans_credit_type_6: int
    enc_loans_credit_type_7: int
    pre_loans5_11: int
    pre_loans3060_0: int
    pre_loans3060_3: int
    pre_loans3060_4: int
    pre_loans3060_6: int
    pre_loans6090_0: int
    pre_loans90_3: int
    pre_loans5_10: int
    pre_loans530_5: int
    pre_loans530_8: int
    pre_loans530_9: int
    pre_loans530_17: int
    flag: int


class Prediction(BaseModel):
    id: int
    result: int
    target: int


@app.get('/status')
def status():
    return "I'm OK"


@app.get('/version')
def version():
    return 'version: 1.0'

@app.post('/predict', response_model=Prediction)
def predict(form: Form):
    df = pd.DataFrame.from_dict([form.dict()])
    y = model.predict(df)

    return {
        'id': form.id,
        'result': y[0],
        'target': form.flag
    }
